//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciiREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asigurat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asigurat()
        {
            this.ConcediuMedical = new HashSet<ConcediuMedical>();
        }
    
        public string CNP { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public bool StareAsigurat { get; set; }
        public string IdStatut { get; set; }
    
        public virtual Statut Statut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConcediuMedical> ConcediuMedical { get; set; }
    }
}
