//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciiREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcediuMedical
    {
        public int Id { get; set; }
        public string CNP { get; set; }
        public System.DateTime DataIncepu { get; set; }
        public System.DateTime DataSfarsit { get; set; }
    
        public virtual Asigurat Asigurat { get; set; }
    }
}
