//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciiREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investigatie
    {
        public string CodInvestigatie { get; set; }
        public string NumeInvestigatie { get; set; }
        public double CostInvestigatie { get; set; }
    }
}
