//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciiREST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalCasEntities : DbContext
    {
        public PortalCasEntities()
            : base("name=PortalCasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Investigatie> Investigatie { get; set; }
        public virtual DbSet<ServiciuMedical> ServiciuMedical { get; set; }
        public virtual DbSet<Statut> Statut { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<Asigurat> Asigurat { get; set; }
        public virtual DbSet<ConcediuMedical> ConcediuMedical { get; set; }
        public virtual DbSet<Spital> Spital { get; set; }
        public virtual DbSet<DateRaportSpital> DateRaportSpital { get; set; }
    }
}
