//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciiREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiciuMedical
    {
        public string CodServiciu { get; set; }
        public string NumeServiciu { get; set; }
        public double CostServiciu { get; set; }
    }
}
