//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciiREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spital()
        {
            this.DateRaportSpital = new HashSet<DateRaportSpital>();
        }
    
        public string IdSpital { get; set; }
        public string NumeSpital { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DateRaportSpital> DateRaportSpital { get; set; }
    }
}
